apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-test
  name: pod-test
  namespace: devops-tools
spec:
  containers:
  - image: docker.io/nginx:latest
    name: pod-test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
